### PR TITLE
Added method for 'Get Board Updates' plus a lot of refactoring

### PR DESCRIPTION
**Pull request by HDauven**
Added support for the 'Get Board Updates'. This method checks your board version against the current board version, and sends updates if these exist within the most up to date board.

There is subtle difference between this method and the 'Get Newer If Exists' method, namely that 'Get Newer If Exists' sends the entire board structure. I've added this to the README.md for clarification.

See the Leankit documentation for further information:
[Get Newer Board If Exists](https://support.leankit.com/hc/en-us/articles/204412753-Get-Newer-Board-If-Exists)
[Get Board Updates](https://support.leankit.com/hc/en-us/articles/212628217-Get-Board-Updates)

Furthermore, the Leankit API doc url was no longer available. This has been updated too with the new URL.

Kind regards.

**Update:**
Removed all the endpoints from their respective modules and placed them in a separate module called 'Endpoint'. This module also provides an API URL formatting method, so that all the gsub code could be removed from their respective modules.

Rspec 'it ... do' descriptions have been rewritten.

**Update 2:**
I made a new version of the 'format_url' method. This new method is called 'build_api_endpoint' and accepts the URL arguments in the form of a hash. The keys in this hash are symbols, instead of a strings.

Note: The updates in this pull request make use of features that are incompatible with pre-Ruby 2.0 versions.

### CODE REVIEW

**Comment by mlainez** [comment]
Thanks! I'll review and merge this week-end. If you're interested in becoming a maintainer for this gem let me know.

**Comment by HDauven** [comment]
Hey @mlainez,
I'm relatively new to Ruby, so please scrutinize the code I submitted to the max. 
If my additions and coding style are to your liking, I'd gladly be a maintainer for this gem. :-)

**Comment by mlainez** [comment]
Looks good to me.

**Comment by HDauven** [comment]
@mlainez I just realised that the way I implemented the endpoint method calls in each Leankit component module isn't that great. People should be able to pass in a hash. 

If I implement it that way, they don't need to worry about the order in which they pass in arguments to calls. I'll try to update it in the coming week. :)

**Pull request merged**
